apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coming-soon

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: coming-soon-html
    files:
      - index.html

generatorOptions:
  disableNameSuffixHash: true
